<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // \App\Models\User::factory(10)->create();

        // \App\Models\User::factory()->create([
        //     'name' => 'Test User',
        //     'email' => 'test@example.com',
        // ]);


        
        
        $sql = 'INSERT INTO variations (`type`, `name`) VALUES
        ("Wheel Brand","1AV"),
        ("Wheel Brand","2Crave"),
        ("Wheel Brand","305 Forged"),
        ("Wheel Brand","4Play"),
        ("Wheel Brand","4Play Forged"),
        ("Wheel Brand","4Play OE Wheels"),
        ("Wheel Brand","4Play Sport"),
        ("Wheel Brand","6Performance"),
        ("Wheel Brand","949 Racing"),
        ("Wheel Brand","9SiX9"),
        ("Wheel Brand","ABS Wheels"),
        ("Wheel Brand","Ace Wheels"),
        ("Wheel Brand","ADR"),
        ("Wheel Brand","Advan Racing"),
        ("Wheel Brand","Aero"),
        ("Wheel Brand","AEV"),
        ("Wheel Brand","Akuza"),
        ("Wheel Brand","Alcoa"),
        ("Wheel Brand","Alloy Ion"),
        ("Wheel Brand","Amani Forged"),
        ("Wheel Brand","American Elite"),
        ("Wheel Brand","American Force"),
        ("Wheel Brand","American Muscle"),
        ("Wheel Brand","American Offroad"),
        ("Wheel Brand","American Outlaw"),
        ("Wheel Brand","American Racing"),
        ("Wheel Brand","American Racing ATX"),
        ("Wheel Brand","American Racing Vintage"),
        ("Wheel Brand","American Truxx"),
        ("Wheel Brand","American Truxx Forged"),
        ("Wheel Brand","AMR"),
        ("Wheel Brand","Anthem Off-Road"),
        ("Wheel Brand","Aodhan"),
        ("Wheel Brand","ARC"),
        ("Wheel Brand","ARE"),
        ("Wheel Brand","ARKON OFF-ROAD"),
        ("Wheel Brand","Armed Offroad"),
        ("Wheel Brand","Art In Motion"),
        ("Wheel Brand","Asanti"),
        ("Wheel Brand","Asanti Black"),
        ("Wheel Brand","Asanti Offroad"),
        ("Wheel Brand","Atara Racing"),
        ("Wheel Brand","Avant Garde"),
        ("Wheel Brand","Avenue"),
        ("Wheel Brand","AVID1"),
        ("Wheel Brand","Axe"),
        ("Wheel Brand","Axe Forged"),
        ("Wheel Brand","Axe Offroad"),
        ("Wheel Brand","Axis"),
        ("Wheel Brand","Azad"),
        ("Wheel Brand","Azara"),
        ("Wheel Brand","Ballistic"),
        ("Wheel Brand","Bart Wheels"),
        ("Wheel Brand","Bassett"),
        ("Wheel Brand","Bazo"),
        ("Wheel Brand","BBS"),
        ("Wheel Brand","BBY Offroad"),
        ("Wheel Brand","BC Forged"),
        ("Wheel Brand","Bcr Wheels"),
        ("Wheel Brand","BG Rod Works"),
        ("Wheel Brand","Billet Specialties"),
        ("Wheel Brand","Black Iron"),
        ("Wheel Brand","Black Rhino"),
        ("Wheel Brand","Black Rock"),
        ("Wheel Brand","Blaque Diamond"),
        ("Wheel Brand","BMF"),
        ("Wheel Brand","Bold"),
        ("Wheel Brand","Borghini"),
        ("Wheel Brand","Boss"),
        ("Wheel Brand","Boyd Coddington"),
        ("Wheel Brand","Brada"),
        ("Wheel Brand","Brute"),
        ("Wheel Brand","Budnik"),
        ("Wheel Brand","BZO"),
        ("Wheel Brand","Cali Offroad"),
        ("Wheel Brand","Capri Luxury"),
        ("Wheel Brand","Cavallo"),
        ("Wheel Brand","Centerline"),
        ("Wheel Brand","Centerline Forged"),
        ("Wheel Brand","Concept One"),
        ("Wheel Brand","Corleone Forged"),
        ("Wheel Brand","Cosmis Racing"),
        ("Wheel Brand","Cragar"),
        ("Wheel Brand","Cratus"),
        ("Wheel Brand","Cruiser Alloy"),
        ("Wheel Brand","Curva"),
        ("Wheel Brand","Dale Earnhart Jr"),
        ("Wheel Brand","Dcenti"),
        ("Wheel Brand","Dcenti Offroad"),
        ("Wheel Brand","Devino"),
        ("Wheel Brand","DFD"),
        ("Wheel Brand","Diablo"),
        ("Wheel Brand","Diablo Offroad"),
        ("Wheel Brand","Diamo"),
        ("Wheel Brand","Dick Cepek"),
        ("Wheel Brand","DIP"),
        ("Wheel Brand","Dirty Life"),
        ("Wheel Brand","Dolce"),
        ("Wheel Brand","DPR"),
        ("Wheel Brand","DPS Offroad"),
        ("Wheel Brand","Drag"),
        ("Wheel Brand","Drifz"),
        ("Wheel Brand","Driv"),
        ("Wheel Brand","Dropstars"),
        ("Wheel Brand","Dropstars Forged"),
        ("Wheel Brand","DUB"),
        ("Wheel Brand","DV8 Offroad"),
        ("Wheel Brand","DWG Offroad"),
        ("Wheel Brand","DWT"),
        ("Wheel Brand","DX4"),
        ("Wheel Brand","Eagle Alloy"),
        ("Wheel Brand","Eclipse Replica"),
        ("Wheel Brand","Elure"),
        ("Wheel Brand","Enkei"),
        ("Wheel Brand","Enthuze"),
        ("Wheel Brand","Envy"),
        ("Wheel Brand","Evil Industries"),
        ("Wheel Brand","Extreme Force"),
        ("Wheel Brand","Extreme Offset"),
        ("Wheel Brand","F1R"),
        ("Wheel Brand","Factory Reproductions"),
        ("Wheel Brand","Falcon Off-Road"),
        ("Wheel Brand","Fast HD"),
        ("Wheel Brand","Fast Wheels"),
        ("Wheel Brand","Ferrada"),
        ("Wheel Brand","Fifteen52"),
        ("Wheel Brand","Fifteen52 Offroad"),
        ("Wheel Brand","Fittipaldi"),
        ("Wheel Brand","Fittipaldi Offroad"),
        ("Wheel Brand","Focal"),
        ("Wheel Brand","Foose"),
        ("Wheel Brand","Force Form By American Force"),
        ("Wheel Brand","Force Off-Road"),
        ("Wheel Brand","Forged Ion"),
        ("Wheel Brand","Forgestar"),
        ("Wheel Brand","Forgiato"),
        ("Wheel Brand","Forte"),
        ("Wheel Brand","Fuel"),
        ("Wheel Brand","Fuel Forged"),
        ("Wheel Brand","Full Throttle"),
        ("Wheel Brand","G-FX"),
        ("Wheel Brand","G-Line"),
        ("Wheel Brand","Gear"),
        ("Wheel Brand","Gear Forged"),
        ("Wheel Brand","Gear Off-Road"),
        ("Wheel Brand","Gianelle"),
        ("Wheel Brand","Gianna"),
        ("Wheel Brand","Gima"),
        ("Wheel Brand","Giovanna"),
        ("Wheel Brand","GM"),
        ("Wheel Brand","Gram Lights"),
        ("Wheel Brand","Granite Alloy"),
        ("Wheel Brand","Greg Weld"),
        ("Wheel Brand","Grid"),
        ("Wheel Brand","GT Offroad"),
        ("Wheel Brand","GTS"),
        ("Wheel Brand","Hardcore Offroad"),
        ("Wheel Brand","Hardrock"),
        ("Wheel Brand","Hartes Metal Offroad"),
        ("Wheel Brand","Havok"),
        ("Wheel Brand","Hayashi Racing"),
        ("Wheel Brand","HD"),
        ("Wheel Brand","Hd Luxxx"),
        ("Wheel Brand","HD Offroad"),
        ("Wheel Brand","HD-PRO"),
        ("Wheel Brand","HD-PRO Forged"),
        ("Wheel Brand","Helo"),
        ("Wheel Brand","Heritage"),
        ("Wheel Brand","Hostile"),
        ("Wheel Brand","Hostile Forged"),
        ("Wheel Brand","HRE FlowForm"),
        ("Wheel Brand","HSR"),
        ("Wheel Brand","Hunter Offroad"),
        ("Wheel Brand","Icon"),
        ("Wheel Brand","Icon Alloys"),
        ("Wheel Brand","IKon"),
        ("Wheel Brand","Impact"),
        ("Wheel Brand","Impact Offroad"),
        ("Wheel Brand","Incubus"),
        ("Wheel Brand","Insane Offroad"),
        ("Wheel Brand","Intro"),
        ("Wheel Brand","Ion Bilt"),
        ("Wheel Brand","Japan Racing"),
        ("Wheel Brand","Jegs"),
        ("Wheel Brand","Jesse James"),
        ("Wheel Brand","JNC"),
        ("Wheel Brand","JR"),
        ("Wheel Brand","JTX Forged"),
        ("Wheel Brand","K2 Offroad"),
        ("Wheel Brand","Kansei"),
        ("Wheel Brand","Kansei Off Road"),
        ("Wheel Brand","Karma Kustoms"),
        ("Wheel Brand","Karma Offroad"),
        ("Wheel Brand","Katana"),
        ("Wheel Brand","KG1 Forged"),
        ("Wheel Brand","King"),
        ("Wheel Brand","Klutch Offroad"),
        ("Wheel Brand","KMC"),
        ("Wheel Brand","KO"),
        ("Wheel Brand","Koko Kuture"),
        ("Wheel Brand","Konig"),
        ("Wheel Brand","Krank"),
        ("Wheel Brand","Kraze"),
        ("Wheel Brand","Kronik"),
        ("Wheel Brand","KX"),
        ("Wheel Brand","Lenso"),
        ("Wheel Brand","Lethal Offroad"),
        ("Wheel Brand","Level 8"),
        ("Wheel Brand","Lexani"),
        ("Wheel Brand","Liberty Forged"),
        ("Wheel Brand","Liquid Metal"),
        ("Wheel Brand","Lock Offroad Wheels"),
        ("Wheel Brand","Lonestar"),
        ("Wheel Brand","LRG"),
        ("Wheel Brand","Luxxx Alloys"),
        ("Wheel Brand","Luxxx HD"),
        ("Wheel Brand","Mamba"),
        ("Wheel Brand","Mangels"),
        ("Wheel Brand","Marquee Luxury"),
        ("Wheel Brand","Massiv"),
        ("Wheel Brand","Massiv Offroad"),
        ("Wheel Brand","Mayhem"),
        ("Wheel Brand","Mazzi"),
        ("Wheel Brand","MB Wheels"),
        ("Wheel Brand","Metal Mulisha"),
        ("Wheel Brand","Method"),
        ("Wheel Brand","Mickey Thompson"),
        ("Wheel Brand","Milanni"),
        ("Wheel Brand","MKW"),
        ("Wheel Brand","MMD"),
        ("Wheel Brand","Momo"),
        ("Wheel Brand","Monster Energy"),
        ("Wheel Brand","Monster Offroad"),
        ("Wheel Brand","Motegi"),
        ("Wheel Brand","Motiv"),
        ("Wheel Brand","Motiv Offroad"),
        ("Wheel Brand","Moto Metal"),
        ("Wheel Brand","Motto"),
        ("Wheel Brand","MRR"),
        ("Wheel Brand","MRW"),
        ("Wheel Brand","MSR"),
        ("Wheel Brand","MST"),
        ("Wheel Brand","Mudster Offroad"),
        ("Wheel Brand","MVX Offroad"),
        ("Wheel Brand","Nascar"),
        ("Wheel Brand","Neuspeed"),
        ("Wheel Brand","Niche"),
        ("Wheel Brand","NS"),
        ("Wheel Brand","OE Creations"),
        ("Wheel Brand","OE Performance"),
        ("Wheel Brand","OE Replicas"),
        ("Wheel Brand","OE Revolution"),
        ("Wheel Brand","OEM Wheels"),
        ("Wheel Brand","Off Road Monster"),
        ("Wheel Brand","Onyx Offroad"),
        ("Wheel Brand","Pacer"),
        ("Wheel Brand","Panther"),
        ("Wheel Brand","Panther Offroad"),
        ("Wheel Brand","PDW"),
        ("Wheel Brand","Pinnacle"),
        ("Wheel Brand","Platinum"),
        ("Wheel Brand","Pro Comp"),
        ("Wheel Brand","Proline"),
        ("Wheel Brand","Pure Grit"),
        ("Wheel Brand","Quadratec"),
        ("Wheel Brand","Raceline"),
        ("Wheel Brand","Raptor"),
        ("Wheel Brand","Ravetti"),
        ("Wheel Brand","RBP"),
        ("Wheel Brand","RBP Forged"),
        ("Wheel Brand","Rebel Offroad"),
        ("Wheel Brand","Rebel Racing"),
        ("Wheel Brand","Red Dirt Road"),
        ("Wheel Brand","Reika"),
        ("Wheel Brand","Relations Race Wheels"),
        ("Wheel Brand","Remington"),
        ("Wheel Brand","Rennen International"),
        ("Wheel Brand","Replica"),
        ("Wheel Brand","Replica Tech"),
        ("Wheel Brand","Reps"),
        ("Wheel Brand","Rev"),
        ("Wheel Brand","Rev Offroad"),
        ("Wheel Brand","Rev Replicas"),
        ("Wheel Brand","Revenge Offroad"),
        ("Wheel Brand","Ridler"),
        ("Wheel Brand","Road Ready"),
        ("Wheel Brand","Rock Trix"),
        ("Wheel Brand","Rocket Racing"),
        ("Wheel Brand","Rockstarr"),
        ("Wheel Brand","Rocktrix"),
        ("Wheel Brand","Rocky Ridge"),
        ("Wheel Brand","Rohana"),
        ("Wheel Brand","Rosso"),
        ("Wheel Brand","Rotiform"),
        ("Wheel Brand","Rough Country"),
        ("Wheel Brand","Roush"),
        ("Wheel Brand","RRW"),
        ("Wheel Brand","RSSW"),
        ("Wheel Brand","RTR"),
        ("Wheel Brand","RTX"),
        ("Wheel Brand","RTX Offroad"),
        ("Wheel Brand","RTX R-Spec"),
        ("Wheel Brand","Ruff"),
        ("Wheel Brand","Ruffino"),
        ("Wheel Brand","Ruffino Hard"),
        ("Wheel Brand","Rugged Ridge"),
        ("Wheel Brand","Savage"),
        ("Wheel Brand","Savage Offroad"),
        ("Wheel Brand","Savini"),
        ("Wheel Brand","SCA Performance"),
        ("Wheel Brand","Scorpion"),
        ("Wheel Brand","SCS"),
        ("Wheel Brand","Sendel"),
        ("Wheel Brand","Sevizia"),
        ("Wheel Brand","Shift"),
        ("Wheel Brand","Shogun"),
        ("Wheel Brand","Sota"),
        ("Wheel Brand","Sothis"),
        ("Wheel Brand","Spec-1"),
        ("Wheel Brand","Specialty Forged"),
        ("Wheel Brand","Spyderlock"),
        ("Wheel Brand","SSW"),
        ("Wheel Brand","Stage Wheels"),
        ("Wheel Brand","Starr"),
        ("Wheel Brand","Status"),
        ("Wheel Brand","Staz Works"),
        ("Wheel Brand","Stealth Custom Series"),
        ("Wheel Brand","Stealth Forged"),
        ("Wheel Brand","Steel"),
        ("Wheel Brand","Steel Off-Road"),
        ("Wheel Brand","Strada"),
        ("Wheel Brand","Strada Replicas"),
        ("Wheel Brand","Summit"),
        ("Wheel Brand","SVE"),
        ("Wheel Brand","Tactik"),
        ("Wheel Brand","TIS"),
        ("Wheel Brand","TIS Forged"),
        ("Wheel Brand","Touren"),
        ("Wheel Brand","Toxic"),
        ("Wheel Brand","TR Motorsport"),
        ("Wheel Brand","Trail Master"),
        ("Wheel Brand","TSW"),
        ("Wheel Brand","Tuff"),
        ("Wheel Brand","Tuscany"),
        ("Wheel Brand","Twisted Offroad"),
        ("Wheel Brand","U.S. Wheel"),
        ("Wheel Brand","U2"),
        ("Wheel Brand","Ultimate Performance"),
        ("Wheel Brand","Ultra"),
        ("Wheel Brand","Ultra Xtreme"),
        ("Wheel Brand","Unique"),
        ("Wheel Brand","US Mags"),
        ("Wheel Brand","USA"),
        ("Wheel Brand","USA Forged"),
        ("Wheel Brand","V-Rock"),
        ("Wheel Brand","V-Tec"),
        ("Wheel Brand","Variant"),
        ("Wheel Brand","Varro"),
        ("Wheel Brand","VCT"),
        ("Wheel Brand","Velgen"),
        ("Wheel Brand","Velocity"),
        ("Wheel Brand","Venom"),
        ("Wheel Brand","VenomRex"),
        ("Wheel Brand","Venti"),
        ("Wheel Brand","Verde"),
        ("Wheel Brand","Versante"),
        ("Wheel Brand","Versus Racing"),
        ("Wheel Brand","Vision"),
        ("Wheel Brand","Volk"),
        ("Wheel Brand","Vors"),
        ("Wheel Brand","Vorsteiner"),
        ("Wheel Brand","Vortek"),
        ("Wheel Brand","Vossen"),
        ("Wheel Brand","Voxx"),
        ("Wheel Brand","Voxx Replicas"),
        ("Wheel Brand","VTX Offroad"),
        ("Wheel Brand","Walker Evans"),
        ("Wheel Brand","WedsSport"),
        ("Wheel Brand","Weld"),
        ("Wheel Brand","Weld Off-Road"),
        ("Wheel Brand","Weld Racing"),
        ("Wheel Brand","Weld XT Forged"),
        ("Wheel Brand","Western"),
        ("Wheel Brand","Wheel Replicas"),
        ("Wheel Brand","White Diamond"),
        ("Wheel Brand","Wicked Offroad"),
        ("Wheel Brand","Work"),
        ("Wheel Brand","Worx"),
        ("Wheel Brand","Xcess"),
        ("Wheel Brand","XD"),
        ("Wheel Brand","XF Flow"),
        ("Wheel Brand","XF Forged"),
        ("Wheel Brand","XF Offroad"),
        ("Wheel Brand","XO"),
        ("Wheel Brand","Xtreme"),
        ("Wheel Brand","Xtreme Force"),
        ("Wheel Brand","Xtreme Forged"),
        ("Wheel Brand","Xtreme Mudder"),
        ("Wheel Brand","XXR"),
        ("Wheel Brand","Zenas"),
        ("Wheel Brand","Zenetti"),
        ("Wheel Brand","Zinik"),
        ("Spacers","0.25"),
        ("Spacers","0.5"),
        ("Spacers","0.75"),
        ("Spacers","1.25"),
        ("Spacers","1.5"),
        ("Spacers","1.75"),
        ("Spacers","10mm"),
        ("Spacers","12mm"),
        ("Spacers","13mm"),
        ("Spacers","14mm"),
        ("Spacers","15mm"),
        ("Spacers","18mm"),
        ("Spacers","19mm"),
        ("Spacers","1"),
        ("Spacers","2.25"),
        ("Spacers","2.5"),
        ("Spacers","2.75"),
        ("Spacers","20mm"),
        ("Spacers","22mm"),
        ("Spacers","24mm"),
        ("Spacers","25mm"),
        ("Spacers","2"),
        ("Spacers","3.5"),
        ("Spacers","30mm"),
        ("Spacers","35mm"),
        ("Spacers","38mm"),
        ("Spacers","3mm"),
        ("Spacers","3"),
        ("Spacers","40mm"),
        ("Spacers","43mm"),
        ("Spacers","44mm"),
        ("Spacers","45mm"),
        ("Spacers","4mm"),
        ("Spacers","4"),
        ("Spacers","50mm"),
        ("Spacers","5mm"),
        ("Spacers","6mm"),
        ("Spacers","7mm"),
        ("Spacers","8mm"),
        ("Spacers","9mm"),
        ("Spacers",">2"),
        ("Spacers",">50mm"),
        ("Spacers","None"),
        ("Type of Stance","Aggressive > 1  outside fender"),
        ("Type of Stance","Flush"),
        ("Type of Stance","Hella Stance >5 "),
        ("Type of Stance","HellaFlush"),
        ("Type of Stance","Nearly Flush"),
        ("Type of Stance","Slightly Aggressive"),
        ("Type of Stance","Super Aggressive 3 -5 "),
        ("Type of Stance","Tucked"),
        ("Wheel Offset","-200mm"),
        ("Wheel Offset","-81mm"),
        ("Wheel Offset","-76mm"),
        ("Wheel Offset","-75mm"),
        ("Wheel Offset","-73mm"),
        ("Wheel Offset","-70mm"),
        ("Wheel Offset","-51mm"),
        ("Wheel Offset","-45mm"),
        ("Wheel Offset","-44mm"),
        ("Wheel Offset","-43mm"),
        ("Wheel Offset","-40mm"),
        ("Wheel Offset","-38mm"),
        ("Wheel Offset","-25mm"),
        ("Wheel Offset","-24mm"),
        ("Wheel Offset","-19mm"),
        ("Wheel Offset","-18mm"),
        ("Wheel Offset","-13mm"),
        ("Wheel Offset","-12mm"),
        ("Wheel Offset","-10mm"),
        ("Wheel Offset","-6mm"),
        ("Wheel Offset","-5mm"),
        ("Wheel Offset","0mm"),
        ("Wheel Offset","-0mm"),
        ("Wheel Offset","1mm"),
        ("Wheel Offset","5mm"),
        ("Wheel Offset","6mm"),
        ("Wheel Offset","10mm"),
        ("Wheel Offset","12mm"),
        ("Wheel Offset","14mm"),
        ("Wheel Offset","15mm"),
        ("Wheel Offset","18mm"),
        ("Wheel Offset","20mm"),
        ("Wheel Offset","22mm"),
        ("Wheel Offset","24mm"),
        ("Wheel Offset","25mm"),
        ("Wheel Offset","27mm"),
        ("Wheel Offset","28mm"),
        ("Wheel Offset","30mm"),
        ("Wheel Offset","31mm"),
        ("Wheel Offset","32mm"),
        ("Wheel Offset","33mm"),
        ("Wheel Offset","34mm"),
        ("Wheel Offset","35mm"),
        ("Wheel Offset","38mm"),
        ("Wheel Offset","40mm"),
        ("Wheel Offset","42mm"),
        ("Wheel Offset","44mm"),
        ("Wheel Offset","45mm"),
        ("Tire Width","0"),
        ("Tire Width","7.5"),
        ("Tire Width","8.5"),
        ("Tire Width","9.5"),
        ("Tire Width","10.5"),
        ("Tire Width","11.5"),
        ("Tire Width","12.5"),
        ("Tire Width","13.5"),
        ("Tire Width","14"),
        ("Tire Width","14.5"),
        ("Tire Width","15.5"),
        ("Tire Width","16"),
        ("Tire Width","16.5"),
        ("Tire Width","17"),
        ("Tire Width","18.5"),
        ("Tire Width","19.5"),
        ("Tire Width","20"),
        ("Tire Width","25"),
        ("Tire Width","27"),
        ("Tire Width","30"),
        ("Tire Width","35"),
        ("Tire Width","40"),
        ("Tire Width","45"),
        ("Tire Width","50"),
        ("Tire Width","55"),
        ("Tire Width","60"),
        ("Tire Width","65"),
        ("Tire Width","70"),
        ("Tire Width","75"),
        ("Tire Width","80"),
        ("Tire Width","85"),
        ("Tire Height","0"),
        ("Tire Height","25"),
        ("Tire Height","26"),
        ("Tire Height","27"),
        ("Tire Height","29"),
        ("Tire Height","30"),
        ("Tire Height","31"),
        ("Tire Height","32"),
        ("Tire Height","33"),
        ("Tire Height","34"),
        ("Tire Height","35"),
        ("Tire Height","36"),
        ("Tire Height","37"),
        ("Tire Height","38"),
        ("Tire Height","39"),
        ("Tire Height","40"),
        ("Tire Height","41"),
        ("Tire Height","42"),
        ("Tire Height","44"),
        ("Tire Height","46"),
        ("Tire Height","53"),
        ("Tire Height","54"),
        ("Tire Height","145mm"),
        ("Tire Height","155mm"),
        ("Tire Height","165mm"),
        ("Tire Height","175mm"),
        ("Tire Height","185mm"),
        ("Tire Height","195mm"),
        ("Tire Height","205mm"),
        ("Tire Height","215mm"),
        ("Tire Height","225mm"),
        ("Tire Height","235mm"),
        ("Tire Height","245mm"),
        ("Tire Height","255mm"),
        ("Tire Height","265mm"),
        ("Tire Height","275mm"),
        ("Tire Height","285mm"),
        ("Tire Height","295mm"),
        ("Tire Height","305mm"),
        ("Tire Height","315mm"),
        ("Tire Height","325mm"),
        ("Tire Height","335mm"),
        ("Tire Height","345mm"),
        ("Tire Height","355mm"),
        ("Tire Height","365mm"),
        ("Tire Height","375mm"),
        ("Tire Height","385mm"),
        ("Tire Height","395mm"),
        ("Tire Height","405mm"),
        ("Wheel Diameter","13"),
        ("Wheel Diameter","14"),
        ("Wheel Diameter","15"),
        ("Wheel Diameter","16"),
        ("Wheel Diameter","16.5"),
        ("Wheel Diameter","17"),
        ("Wheel Diameter","18"),
        ("Wheel Diameter","19"),
        ("Wheel Diameter","20"),
        ("Wheel Diameter","21"),
        ("Wheel Diameter","22"),
        ("Wheel Diameter","24"),
        ("Wheel Diameter","26"),
        ("Wheel Diameter","28"),
        ("Wheel Diameter","30"),
        ("Wheel Width","5"),
        ("Wheel Width","5.5"),
        ("Wheel Width","6"),
        ("Wheel Width","6.5"),
        ("Wheel Width","7"),
        ("Wheel Width","7.5"),
        ("Wheel Width","8"),
        ("Wheel Width","8.25"),
        ("Wheel Width","8.5"),
        ("Wheel Width","9"),
        ("Wheel Width","9.5"),
        ("Wheel Width","9.75"),
        ("Wheel Width","10"),
        ("Wheel Width","10.5"),
        ("Wheel Width","11"),
        ("Wheel Width","11.5"),
        ("Wheel Width","12"),
        ("Wheel Width","12.5"),
        ("Wheel Width","13"),
        ("Wheel Width","14"),
        ("Wheel Width","15"),
        ("Wheel Width","16"),
        ("Wheel Width","18"),
        ("Tire Brand","Accelera"),
        ("Tire Brand","Achilles"),
        ("Tire Brand","Advanta"),
        ("Tire Brand","Altenzo"),
        ("Tire Brand","American Tourer"),
        ("Tire Brand","Americus"),
        ("Tire Brand","AMP"),
        ("Tire Brand","Antares"),
        ("Tire Brand","Aoteli"),
        ("Tire Brand","Aplus"),
        ("Tire Brand","Apollo"),
        ("Tire Brand","Aptany"),
        ("Tire Brand","Arctic Claw"),
        ("Tire Brand","Ardent"),
        ("Tire Brand","Arroyo"),
        ("Tire Brand","Aspen"),
        ("Tire Brand","Atlander"),
        ("Tire Brand","Atlas"),
        ("Tire Brand","Atrezzo"),
        ("Tire Brand","Atturo"),
        ("Tire Brand","Austone"),
        ("Tire Brand","Autoguard"),
        ("Tire Brand","Axiom"),
        ("Tire Brand","Back Country"),
        ("Tire Brand","Barum"),
        ("Tire Brand","BFGoodrich"),
        ("Tire Brand","Big O"),
        ("Tire Brand","Black Bear"),
        ("Tire Brand","Black Hawk"),
        ("Tire Brand","Black Lion"),
        ("Tire Brand","Boristar"),
        ("Tire Brand","Bridgestone"),
        ("Tire Brand","Briway"),
        ("Tire Brand","Capitol"),
        ("Tire Brand","Centara"),
        ("Tire Brand","Centennial"),
        ("Tire Brand","Chaparral"),
        ("Tire Brand","Comforser"),
        ("Tire Brand","Continental"),
        ("Tire Brand","Cooper"),
        ("Tire Brand","Cordovan"),
        ("Tire Brand","Corsa"),
        ("Tire Brand","Cosmo"),
        ("Tire Brand","Crossland"),
        ("Tire Brand","Crossleader"),
        ("Tire Brand","Crosswind"),
        ("Tire Brand","Dayton"),
        ("Tire Brand","Dcenti"),
        ("Tire Brand","Dean"),
        ("Tire Brand","Deestone"),
        ("Tire Brand","Definity"),
        ("Tire Brand","Delinte"),
        ("Tire Brand","Delium"),
        ("Tire Brand","Delta"),
        ("Tire Brand","Dextero"),
        ("Tire Brand","Dick Cepek"),
        ("Tire Brand","Doublestar"),
        ("Tire Brand","Douglas"),
        ("Tire Brand","Duck Commander"),
        ("Tire Brand","Dunlop"),
        ("Tire Brand","Duraturn"),
        ("Tire Brand","Duro"),
        ("Tire Brand","Durun"),
        ("Tire Brand","Eldorado"),
        ("Tire Brand","Evergreen"),
        ("Tire Brand","Falken"),
        ("Tire Brand","Farroad"),
        ("Tire Brand","Federal"),
        ("Tire Brand","Fierce"),
        ("Tire Brand","Firemax"),
        ("Tire Brand","Firestone"),
        ("Tire Brand","Forceland"),
        ("Tire Brand","Forceum"),
        ("Tire Brand","Forgiato"),
        ("Tire Brand","Fortune"),
        ("Tire Brand","Free Passer"),
        ("Tire Brand","Fuel"),
        ("Tire Brand","Fullrun"),
        ("Tire Brand","Fullway"),
        ("Tire Brand","Fury Offroad"),
        ("Tire Brand","Fusion"),
        ("Tire Brand","Futura"),
        ("Tire Brand","Fuzion"),
        ("Tire Brand","GBC"),
        ("Tire Brand","General"),
        ("Tire Brand","Geo Tour"),
        ("Tire Brand","Geo-Trac"),
        ("Tire Brand","Ginell"),
        ("Tire Brand","Gladiator"),
        ("Tire Brand","Goalstar"),
        ("Tire Brand","Goldway"),
        ("Tire Brand","Goodride"),
        ("Tire Brand","Goodtrip"),
        ("Tire Brand","Goodyear"),
        ("Tire Brand","Grenlander"),
        ("Tire Brand","Grit King"),
        ("Tire Brand","Groundspeed"),
        ("Tire Brand","GT Radial"),
        ("Tire Brand","Haida"),
        ("Tire Brand","Hankook"),
        ("Tire Brand","Hercules"),
        ("Tire Brand","Hifly"),
        ("Tire Brand","Interco"),
        ("Tire Brand","Invovic"),
        ("Tire Brand","Ironman"),
        ("Tire Brand","Jinyu"),
        ("Tire Brand","Joyroad"),
        ("Tire Brand","Kanati"),
        ("Tire Brand","Kapsen"),
        ("Tire Brand","Kelly"),
        ("Tire Brand","Kenda"),
        ("Tire Brand","Kinforest"),
        ("Tire Brand","Kingrun"),
        ("Tire Brand","Kpatos"),
        ("Tire Brand","Kumho"),
        ("Tire Brand","Lakesea"),
        ("Tire Brand","Lancaster"),
        ("Tire Brand","Land Golden"),
        ("Tire Brand","Landsail"),
        ("Tire Brand","Landspider"),
        ("Tire Brand","Lanvigator"),
        ("Tire Brand","Laufenn"),
        ("Tire Brand","Leao"),
        ("Tire Brand","Legion"),
        ("Tire Brand","Lexani"),
        ("Tire Brand","Linglong"),
        ("Tire Brand","Lionhart"),
        ("Tire Brand","LuckYear"),
        ("Tire Brand","Mark Ma"),
        ("Tire Brand","Mastercraft"),
        ("Tire Brand","Maxtrac"),
        ("Tire Brand","Maxtrek"),
        ("Tire Brand","Maxxis"),
        ("Tire Brand","Mazama"),
        ("Tire Brand","Mazzini"),
        ("Tire Brand","Michelin"),
        ("Tire Brand","Mickey Thompson"),
        ("Tire Brand","Mile King"),
        ("Tire Brand","Milestar"),
        ("Tire Brand","Miletrip"),
        ("Tire Brand","Mirada"),
        ("Tire Brand","Monster"),
        ("Tire Brand","Motomaster"),
        ("Tire Brand","Mud Claw"),
        ("Tire Brand","Multi Mile"),
        ("Tire Brand","Multi Trac"),
        ("Tire Brand","Muteki"),
        ("Tire Brand","Nankang"),
        ("Tire Brand","National"),
        ("Tire Brand","Neoterra"),
        ("Tire Brand","Nereus"),
        ("Tire Brand","Nexen"),
        ("Tire Brand","Nitto"),
        ("Tire Brand","Nokian"),
        ("Tire Brand","Nordexx"),
        ("Tire Brand","Ohtsu"),
        ("Tire Brand","Open Range"),
        ("Tire Brand","Otani"),
        ("Tire Brand","Other"),
        ("Tire Brand","Pantera"),
        ("Tire Brand","Parnelli Jones"),
        ("Tire Brand","Pathfinder"),
        ("Tire Brand","Patriot"),
        ("Tire Brand","Pinnacle"),
        ("Tire Brand","Pioneer"),
        ("Tire Brand","Pirelli"),
        ("Tire Brand","Pit Bull"),
        ("Tire Brand","Predator"),
        ("Tire Brand","Presa"),
        ("Tire Brand","Primewell"),
        ("Tire Brand","Prinx"),
        ("Tire Brand","Pro Comp"),
        ("Tire Brand","Provider"),
        ("Tire Brand","Radar"),
        ("Tire Brand","Raptor"),
        ("Tire Brand","RBP"),
        ("Tire Brand","Red Dirt Road"),
        ("Tire Brand","Remington"),
        ("Tire Brand","Renegade"),
        ("Tire Brand","Riken"),
        ("Tire Brand","Road One"),
        ("Tire Brand","Roadclaw"),
        ("Tire Brand","Roadcruza"),
        ("Tire Brand","Roadstone"),
        ("Tire Brand","Rockstar"),
        ("Tire Brand","Rough Country"),
        ("Tire Brand","Rovelo"),
        ("Tire Brand","Royal Black"),
        ("Tire Brand","Rydanz"),
        ("Tire Brand","Saferich"),
        ("Tire Brand","Sailun"),
        ("Tire Brand","Semperit"),
        ("Tire Brand","Sentury"),
        ("Tire Brand","Sierra"),
        ("Tire Brand","Starfire"),
        ("Tire Brand","Starsail"),
        ("Tire Brand","Steel Radial"),
        ("Tire Brand","Stock"),
        ("Tire Brand","Sumitomo"),
        ("Tire Brand","Summit"),
        ("Tire Brand","Sunfull"),
        ("Tire Brand","Sunny"),
        ("Tire Brand","Super Swamper"),
        ("Tire Brand","Supermax"),
        ("Tire Brand","Suretrac"),
        ("Tire Brand","TBB"),
        ("Tire Brand","Tbc Neutral"),
        ("Tire Brand","Thunderer"),
        ("Tire Brand","TIS"),
        ("Tire Brand","Toyo Tires"),
        ("Tire Brand","Tracmax"),
        ("Tire Brand","Trail Guide"),
        ("Tire Brand","Trailfinder"),
        ("Tire Brand","Travelstar"),
        ("Tire Brand","Treadwright"),
        ("Tire Brand","Tri-Ace"),
        ("Tire Brand","Triangle"),
        ("Tire Brand","Tuff"),
        ("Tire Brand","Uniroyal"),
        ("Tire Brand","V-netik"),
        ("Tire Brand","Valino"),
        ("Tire Brand","Velozza"),
        ("Tire Brand","Venezia"),
        ("Tire Brand","Venom Power"),
        ("Tire Brand","Vercelli"),
        ("Tire Brand","Versatyre"),
        ("Tire Brand","Vizzoni"),
        ("Tire Brand","Vredestein"),
        ("Tire Brand","Wanli"),
        ("Tire Brand","Westlake"),
        ("Tire Brand","Wild Country"),
        ("Tire Brand","Wild Trail"),
        ("Tire Brand","Windforce"),
        ("Tire Brand","WinRun"),
        ("Tire Brand","Wrangler"),
        ("Tire Brand","XF Off-Road"),
        ("Tire Brand","Yokohama"),
        ("Tire Brand","Zeetex"),
        ("Tire Brand","Zenna"),
        ("Tire Brand","Zestino"),
        ("Tire Brand","Zeta"),
        ("Rubbing","No rubbing or scrubbing"),
        ("Rubbing","Slight rub at full turn"),
        ("Rubbing","Rubs"),
        ("Rubbing","Rubs like crazy but who cares"),
        ("Modification","No Trimming"),
        ("Modification","Minor Plastic Trimming"),
        ("Modification","Major Plastic Trimming"),
        ("Modification","Minor Metal Trimming"),
        ("Modification","Major Metal Trimming"),
        ("Modification","Fenders Rolled"),
        ("Modification","Fenders Rolled and Trimming"),
        ("Suspension","STOCK"),
        ("Suspension","LEVELING KIT"),
        ("Suspension","SUSPENSION LIFT 2.5"),
        ("Suspension","SUSPENSION LIFT 3"),
        ("Suspension","SUSPENSION LIFT 3.5"),
        ("Suspension","SUSPENSION LIFT 4"),
        ("Suspension","SUSPENSION LIFT 4.5"),
        ("Suspension","SUSPENSION LIFT 4.75"),
        ("Suspension","SUSPENSION LIFT 5"),
        ("Suspension","SUSPENSION LIFT 5.5"),
        ("Suspension","SUSPENSION LIFT 6"),
        ("Suspension","SUSPENSION LIFT 6.5"),
        ("Suspension","SUSPENSION LIFT 7"),
        ("Suspension","SUSPENSION LIFT 7.5"),
        ("Suspension","SUSPENSION LIFT 8"),
        ("Suspension","SUSPENSION LIFT 8.5"),
        ("Suspension","SUSPENSION LIFT 9"),
        ("Suspension","SUSPENSION LIFT 9.5"),
        ("Suspension","SUSPENSION LIFT 10"),
        ("Suspension","SUSPENSION LIFT 12"),
        ("Suspension","LIFTED >12"),
        ("Suspension","BODY LIFT 3"),
        ("Suspension","LEVELING KIT & BODY LIFT"),
        ("Suspension","SUSPENSION LIFT 6 & BODY 3"),
        ("Suspension","SUSPENSION LIFT 7 & BODY 3"),
        ("Suspension","SUSPENSION LIFT 7.5 & BODY 3"),
        ("Suspension","LEVEL 2 DROP REAR"),
        ("Suspension","LOWERED ADJ COIL OVERS"),
        ("Suspension","LOWERED ON SPRINGS"),
        ("Suspension","LOWERED 2F / 4R"),
        ("Suspension","LOWERED 3F / 5R"),
        ("Suspension","LOWERED 4F / 6R"),
        ("Suspension","LOWERED 5F / 7R"),
        ("Suspension","LOWERED 6+F / 8+R"),
        ("Suspension","AIR SUSPENSION"),
        ("Suspension Brand","2 Inch Level"),
        ("Suspension Brand","2 inch level"),
        ("Suspension Brand","2.5 inch level"),
        ("Suspension Brand","3 Inch Lift"),
        ("Suspension Brand","326Power"),
        ("Suspension Brand","3rd Coast Suspension"),
        ("Suspension Brand","4 Inch blocks"),
        ("Suspension Brand","4 inch blocks/leveled"),
        ("Suspension Brand","7Twenty"),
        ("Suspension Brand","ADF"),
        ("Suspension Brand","ADS"),
        ("Suspension Brand","AEV"),
        ("Suspension Brand","AKM"),
        ("Suspension Brand","AMS Ãhlins"),
        ("Suspension Brand","AP Sportfahrwerke"),
        ("Suspension Brand","APEX"),
        ("Suspension Brand","APM"),
        ("Suspension Brand","ARK Performance"),
        ("Suspension Brand","AccuAir"),
        ("Suspension Brand","Accuair"),
        ("Suspension Brand","Aev"),
        ("Suspension Brand","Air Force Suspension"),
        ("Suspension Brand","Air Lift Performance"),
        ("Suspension Brand","Air Ride Technologies"),
        ("Suspension Brand","Air Runner"),
        ("Suspension Brand","AirBagIt.com"),
        ("Suspension Brand","Airlinks"),
        ("Suspension Brand","Airtekk"),
        ("Suspension Brand","All roads"),
        ("Suspension Brand","American Made Suspensions"),
        ("Suspension Brand","Atlas"),
        ("Suspension Brand","Auto Spring"),
        ("Suspension Brand","B&G Suspension"),
        ("Suspension Brand","BC Racing"),
        ("Suspension Brand","BDS Suspension"),
        ("Suspension Brand","BLITZ"),
        ("Suspension Brand","BMR Suspension"),
        ("Suspension Brand","BTF fabrication"),
        ("Suspension Brand","Bds Suspension"),
        ("Suspension Brand","Belltech"),
        ("Suspension Brand","Billet"),
        ("Suspension Brand","Bilstein"),
        ("Suspension Brand","Black mountain"),
        ("Suspension Brand","Blackworks"),
        ("Suspension Brand","Body Armor"),
        ("Suspension Brand","Bulletproof Suspension"),
        ("Suspension Brand","CCE"),
        ("Suspension Brand","CCM"),
        ("Suspension Brand","CST"),
        ("Suspension Brand","CXRacing"),
        ("Suspension Brand","Camburg"),
        ("Suspension Brand","Carli Suspension"),
        ("Suspension Brand","Clayton Offroad"),
        ("Suspension Brand","Cognito"),
        ("Suspension Brand","Corksport"),
        ("Suspension Brand","Crown"),
        ("Suspension Brand","Cst"),
        ("Suspension Brand","Cusco"),
        ("Suspension Brand","Custom"),
        ("Suspension Brand","D2 Racing"),
        ("Suspension Brand","DJM"),
        ("Suspension Brand","DNA Motoring"),
        ("Suspension Brand","DNR"),
        ("Suspension Brand","DT ProFab"),
        ("Suspension Brand","Daystar"),
        ("Suspension Brand","Dick Cepek"),
        ("Suspension Brand","Dirt King"),
        ("Suspension Brand","Dobinsons"),
        ("Suspension Brand","Dynofit"),
        ("Suspension Brand","ECCPP"),
        ("Suspension Brand","EVO"),
        ("Suspension Brand","EZ Lift"),
        ("Suspension Brand","Ebay"),
        ("Suspension Brand","Eibach"),
        ("Suspension Brand","Enthuze"),
        ("Suspension Brand","Extreme Suspension"),
        ("Suspension Brand","Ez Lift"),
        ("Suspension Brand","FOX"),
        ("Suspension Brand","Fabtech"),
        ("Suspension Brand","FactionFab"),
        ("Suspension Brand","Fat Bobs Garage"),
        ("Suspension Brand","Firestone"),
        ("Suspension Brand","Foa"),
        ("Suspension Brand","Ford Keys"),
        ("Suspension Brand","Ford Performance Track"),
        ("Suspension Brand","Forge Motorsport"),
        ("Suspension Brand","Fortune Auto"),
        ("Suspension Brand","Fox"),
        ("Suspension Brand","Freedom Off-Road"),
        ("Suspension Brand","Full Throttle Suspension"),
        ("Suspension Brand","Function and Form"),
        ("Suspension Brand","Gaberiel"),
        ("Suspension Brand","Godspeed Project"),
        ("Suspension Brand","Ground Control"),
        ("Suspension Brand","Ground Force"),
        ("Suspension Brand","H&R Suspension"),
        ("Suspension Brand","H&r Suspension"),
        ("Suspension Brand","HKS"),
        ("Suspension Brand","HSD"),
        ("Suspension Brand","Halo"),
        ("Suspension Brand","Havoc Offroad"),
        ("Suspension Brand","Heavy Metal Suspensions"),
        ("Suspension Brand","Hell Bent Steel"),
        ("Suspension Brand","ICON"),
        ("Suspension Brand","IHC"),
        ("Suspension Brand","IHC Suspension"),
        ("Suspension Brand","Icon"),
        ("Suspension Brand","Inez Hotrod Custom TX"),
        ("Suspension Brand","Iron Rock Off Road"),
        ("Suspension Brand","Ironman"),
        ("Suspension Brand","JBA"),
        ("Suspension Brand","JKS"),
        ("Suspension Brand","JKS Manufacturing"),
        ("Suspension Brand","Jks"),
        ("Suspension Brand","John C Garage"),
        ("Suspension Brand","K-Tuned"),
        ("Suspension Brand","KORE"),
        ("Suspension Brand","KSP"),
        ("Suspension Brand","KYB"),
        ("Suspension Brand","Kaotic Concepts"),
        ("Suspension Brand","Kelderman"),
        ("Suspension Brand","King"),
        ("Suspension Brand","King Shocks"),
        ("Suspension Brand","King Springs"),
        ("Suspension Brand","Koni"),
        ("Suspension Brand","Krazy Kustomz"),
        ("Suspension Brand","Kryptonite"),
        ("Suspension Brand","Ksport"),
        ("Suspension Brand","LiftMeister"),
        ("Suspension Brand","Low Range Off-Road"),
        ("Suspension Brand","MOOG"),
        ("Suspension Brand","Mammoth"),
        ("Suspension Brand","Markmc"),
        ("Suspension Brand","MaxSpeedingRods"),
        ("Suspension Brand","MaxTrac"),
        ("Suspension Brand","Maxtrac"),
        ("Suspension Brand","McGaughys"),
        ("Suspension Brand","Mcgaughys"),
        ("Suspension Brand","Metalcloak"),
        ("Suspension Brand","Mixed"),
        ("Suspension Brand","Monroe"),
        ("Suspension Brand","Moog"),
        ("Suspension Brand","Mopar"),
        ("Suspension Brand","MotoFab"),
        ("Suspension Brand","Motofab"),
        ("Suspension Brand","Mountune"),
        ("Suspension Brand","NEO Motorsport"),
        ("Suspension Brand","NEUSPEED"),
        ("Suspension Brand","Nfab"),
        ("Suspension Brand","Nisstec"),
        ("Suspension Brand","OEM"),
        ("Suspension Brand","OME"),
        ("Suspension Brand","Oem"),
        ("Suspension Brand","Old Man Emu"),
        ("Suspension Brand","Other"),
        ("Suspension Brand","PMF"),
        ("Suspension Brand","PMF Suspension"),
        ("Suspension Brand","PRG Products"),
        ("Suspension Brand","Parts Shop MAX"),
        ("Suspension Brand","Pedders"),
        ("Suspension Brand","Performance Accessories"),
        ("Suspension Brand","Pmf"),
        ("Suspension Brand","Powertrix"),
        ("Suspension Brand","Precision European Mototwerks"),
        ("Suspension Brand","Pro Comp"),
        ("Suspension Brand","Pro Tune"),
        ("Suspension Brand","ProRyde"),
        ("Suspension Brand","Proryde"),
        ("Suspension Brand","Pure Performance"),
        ("Suspension Brand","QA1"),
        ("Suspension Brand","Quality Suspension"),
        ("Suspension Brand","RBP"),
        ("Suspension Brand","RCD"),
        ("Suspension Brand","RGX"),
        ("Suspension Brand","RMX"),
        ("Suspension Brand","ROX"),
        ("Suspension Brand","RPG"),
        ("Suspension Brand","RS Performance"),
        ("Suspension Brand","RS-R"),
        ("Suspension Brand","RSK"),
        ("Suspension Brand","Racecomp Engineering"),
        ("Suspension Brand","Rancho"),
        ("Suspension Brand","Rcd"),
        ("Suspension Brand","ReadyLIFT"),
        ("Suspension Brand","Readylift"),
        ("Suspension Brand","Rev9"),
        ("Suspension Brand","RevTek"),
        ("Suspension Brand","Ridetech"),
        ("Suspension Brand","Rize"),
        ("Suspension Brand","Rize Industries"),
        ("Suspension Brand","Road Fury"),
        ("Suspension Brand","Road Magnets"),
        ("Suspension Brand","Rock Krawler"),
        ("Suspension Brand","Rocky Ridge"),
        ("Suspension Brand","Rocky Road Outfitters"),
        ("Suspension Brand","Rough Country"),
        ("Suspension Brand","Roush Performance"),
        ("Suspension Brand","Rtztech"),
        ("Suspension Brand","Rubicon Express"),
        ("Suspension Brand","Rugged Off Road"),
        ("Suspension Brand","Rustys Off-Road"),
        ("Suspension Brand","SD Truck Springs"),
        ("Suspension Brand","SDT"),
        ("Suspension Brand","SKY Manufacturing"),
        ("Suspension Brand","SR Performance"),
        ("Suspension Brand","ST Suspension"),
        ("Suspension Brand","STD"),
        ("Suspension Brand","SUPERLIFT"),
        ("Suspension Brand","Shockworks"),
        ("Suspension Brand","Show Off Motorsports"),
        ("Suspension Brand","Showoff"),
        ("Suspension Brand","Silvers"),
        ("Suspension Brand","Sinister Diesel"),
        ("Suspension Brand","Skyjacker"),
        ("Suspension Brand","Slam Specialities"),
        ("Suspension Brand","Solo Werks"),
        ("Suspension Brand","Southern Truck"),
        ("Suspension Brand","Spindle lift"),
        ("Suspension Brand","Stage 3 Motorsports"),
        ("Suspension Brand","Stance Suspension"),
        ("Suspension Brand","Steeda"),
        ("Suspension Brand","Stock"),
        ("Suspension Brand","Storm"),
        ("Suspension Brand","Straight Axle Swap"),
        ("Suspension Brand","Street Dirt Track"),
        ("Suspension Brand","Street Rays"),
        ("Suspension Brand","Street edge"),
        ("Suspension Brand","Stryker offroad"),
        ("Suspension Brand","Summit Racing"),
        ("Suspension Brand","Superlift"),
        ("Suspension Brand","Supreme Suspensions"),
        ("Suspension Brand","Suspension Specialist"),
        ("Suspension Brand","SuspensionMAXX"),
        ("Suspension Brand","Suspensionmaxx"),
        ("Suspension Brand","Sway-a-Way"),
        ("Suspension Brand","Swift Springs"),
        ("Suspension Brand","Synergy"),
        ("Suspension Brand","TA Technix"),
        ("Suspension Brand","TCS"),
        ("Suspension Brand","TRD"),
        ("Suspension Brand","Tbar crank"),
        ("Suspension Brand","Tcs"),
        ("Suspension Brand","TeraFlex"),
        ("Suspension Brand","Teraflex"),
        ("Suspension Brand","Thuren"),
        ("Suspension Brand","Top Gun Customz"),
        ("Suspension Brand","Top Speed Pro"),
        ("Suspension Brand","Torch"),
        ("Suspension Brand","Torch Off Road"),
        ("Suspension Brand","Torch Offroad"),
        ("Suspension Brand","Torch offroad"),
        ("Suspension Brand","Torsion Keys Cranked"),
        ("Suspension Brand","Torsion bars cranked up"),
        ("Suspension Brand","Total Chaos Fabrication"),
        ("Suspension Brand","Toytec Lifts"),
        ("Suspension Brand","Trail Master"),
        ("Suspension Brand","TrailFX"),
        ("Suspension Brand","Traxda"),
        ("Suspension Brand","Truxxx"),
        ("Suspension Brand","Tuff Country"),
        ("Suspension Brand","USA lift"),
        ("Suspension Brand","Universal Air Suspension"),
        ("Suspension Brand","Unknown"),
        ("Suspension Brand","Viking"),
        ("Suspension Brand","WNP"),
        ("Suspension Brand","Westcott Designs"),
        ("Suspension Brand","Whiplash"),
        ("Suspension Brand","Wicked MFG"),
        ("Suspension Brand","Wicked Mfg"),
        ("Suspension Brand","Woolworth Motorsports"),
        ("Suspension Brand","Wulf Suspensions"),
        ("Suspension Brand","XYZ"),
        ("Suspension Brand","YitaMotor"),
        ("Suspension Brand","Yonaka Motorsports"),
        ("Suspension Brand","Zone")
        ';
        
        DB::statement($sql);
    }
}
